// Build step for the JG Youth Portal.
// Transpiles the editable source (App.js, JSX) into plain browser-ready
// JavaScript (App.compiled.js) so the browser does NOT need to download or
// run the 3MB Babel compiler on every load. Uses the classic React runtime
// (React.createElement) to match how the app was always transpiled.
//
//   Run after EVERY change to App.js:   node build.js
//
const Babel = require('@babel/standalone');
const fs = require('fs');

var src = fs.readFileSync('App.js', 'utf8');
var out;
try {
  out = Babel.transform(src, {
    presets: [['react', { runtime: 'classic' }]],
    // no minification — keep it readable and avoid extra plugins
  }).code;
} catch (e) {
  console.error('BUILD FAILED — App.js did not transpile:', e.message);
  process.exit(1);
}

var header = '// AUTO-GENERATED FROM App.js BY build.js — DO NOT EDIT THIS FILE.\n'
           + '// Edit App.js, then run: node build.js\n';
fs.writeFileSync('App.compiled.js', header + out);
console.log('BUILD OK — App.compiled.js written (' + (header.length + out.length) + ' bytes)');
